ftlabs/correlations-game

- .gitignore
- bin/lib/correlations.js
- create headers const
- remove token query string
> [UPDATE] add request headers, remove token

- .gitignore
- app.js
- bin/lib/game.js
- routes/index.js
- routes/voice.js
Add endpoint and game logic for interaction with google home.
> [Feature] Add voice

- routes/voice.js
Add the ability to answer wit a person's name or by saying the answer number (or answer number + person name).
> [Feature] Add answer options

- bin/lib/game.js
- routes/voice.js
- format options so Google Home says 'two' and not 'second'
- fix issue with names containing dots (e.g. John F. Kelly)
> [Fix] Two vs. second

- bin/lib/game.js
- responses/content.js
- routes/voice.js
(Untested, so let's not merge)
> Refactor to allow for SSML in responses.

- bin/lib/game.js
- routes/voice.js
Response was being returned rather than passed to callback.
> Handle 'win' state

- bin/lib/gameLonger.js
- routes/voice.js
> Correct errors in handling data from database

- routes/voice.js
- treat user input as lowercase for string matching
- do not repeat options if they don't exist
> [BUGFIX] fix lowercase input && no options misunderstanding

- responses/content.js
- routes/voice.js
- amend the text response to not repeat user input
- amend timing between options
- amend lifespan of misheard message
- added homophones for number options
> [Amend] misheard route

- README.md
- bin/lib/game.js
look for env vars to set how many chain links away to start looking for wrong answers.
Defaults to one more than the previous arrangement.
> look for wronger wrong answers

- responses/content.js
- routes/voice.js
Includes:
- Link card to article in answer
- Suggestion chips for question
Refactor:
- Some of the content had to be split to accommodate the cards
Suggested edits for the future:
- Use a list card to have better text formatting
- Add an image || abstract for the article (SAPI?)
> [Feature] mobile cards

- responses/content.js
- routes/voice.js
- added scores
- added followup question to restart game
> [Feature] scores

- responses/content.js
- routes/voice.js
- reword question for mobile
- add names in chips instead of numbers
> [Amend] mobile

- views/correct.hbs
- views/incorrect.hbs
- views/index.hbs
- views/question.hbs
- views/winner.hbs
minor presentation tweak of the no-design index pages
> turn all the action links into buttons

- responses/content.js
- routes/voice.js
- add image with article on phone version
- add FT logo in case of no image
> [Feature] Card images

- bin/lib/game.js
- bin/lib/log-to-spoor.js
- responses/content.js
- routes/voice.js
- Move the disconnect response to the webhook
- Add mention of score when available
- Add tracking, with score at which people give up
> [Fix] Score on disconnect

- routes/index.js
- check that correlations service people returns results
> [Admin] Add health checks

- responses/content.js
- forgot to push text amend in previous PR
> [Amend] change wording

- routes/voice.js
- change `session` to `SESSION`
> [fix] logs

- routes/voice.js
- clarify events in spoor: add type of answer + current score
> [AMEND] spoor tracking

- routes/voice-alexa.js
Add appId from env and change the wording of continue slightly.
> Add appId to alexa

- .gitignore
- routes/voice-alexa.js
Pull request fixing the following issues from submission:
1. Adding default picture when article does not have a picture.
2. Adding stopIntent for start game state.
3. Preventing logic for displays when device does not support it.
> Alexa fixes
